# docker-compose.yml


services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./django
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Для активной разработки, сохраняет изменения
